### PR TITLE
Implement: 'scopes', 'hasScope' and 'hasAnyScopes' method

### PR DESCRIPTION
**Pull request by vlauciani**
Solve Issue: #106

### CODE REVIEW

**Comment by robsontenorio** [comment]
Thanks @vlauciani !

Could you please add tests?

**Comment by vlauciani** [comment]
Hi @robsontenorio 

Tests added!
Could you check If all is ok?

**Comment by robsontenorio** [comment]
There is a missing case test for empty returning. Check the report above.

**Comment by vlauciani** [comment]
The command `composer test:coverage` to test "coverage" doesn't work. It returns an error:
```
bash-5.1#
bash-5.1# composer test:coverage
> php -d pcov.enabled=1 ./vendor/bin/pest --coverage --coverage-clover=.coverage/clover.xml --coverage-html=.coverage

   PASS  KeycloakGuard\Tests\AuthenticateTest
  ✓ authenticates the user when requesting a private endpoint with token
  ✓ authenticates the user when requesting an public endpoint with token
  ✓ forbiden when request a protected endpoint without token
  ✓ laravel default interface for authenticated users
  ✓ laravel default interface for unathenticated users
  ✓ throws a exception when user is not found
  ✓ appends token to the user
  ✓ does not appends token to the user
  ✓ does not load user from database
  ✓ does not load user from database but appends decoded token
  ✓ throws a exception when resource access is not allowed by api
  ✓ ignores resources validation
  ✓ check user has role in resource
  ✓ check user no has role in resource
  ✓ prevent cross roles resources
  ✓ check user has any role in resource
  ✓ check user no has any role in resource
  ✓ prevent cross roles resources with any role
  ✓ check user has scope
  ✓ check user no has scope
  ✓ check user has any scope
  ✓ check user no has any scope
  ✓ custom user retrieve method
  ✓ throws a exception with invalid iat
  ✓ works with leeway
  ✓ authenticates with custom input key
  ✓ authentication prefers bearer token over with custom input key

  Tests:  27 passed
  Time:   0.95s


   ERROR  No code coverage driver is available.
Script php -d pcov.enabled=1 ./vendor/bin/pest --coverage --coverage-clover=.coverage/clover.xml --coverage-html=.coverage handling the test:coverage event returned with error code 1
bash-5.1#
bash-5.1#
```

**Comment by robsontenorio** [comment]
Thanks !

**Pull request merged**
