### PR TITLE
Feature: allow create / update users on the API users table with autenticated token

### PR DESCRIPTION
**Pull request by frital**
This PR aims to, as an option, allow the API to create / update the authenticated user in the local users table.
To achieve this, its possible to inform a custom method on a custom UserProvider, that will be called instead `retrieveByCredentials` and will receive the complete decoded token as parameter, not just the credentials.

### CODE REVIEW

**Comment by frital** [comment]
Hi @robsontenorio ! Any special reason to not accept this PR? It is out of scope or something missing? Pls let me know! Thx in advance!

**Comment by frital** [comment]
Alo @robsontenorio ! Tudo bem? Alguma razao específica pra nao querer aceitar o PR? Ou só correria mesmo? :)
Muito obrigado por antecipacao, e no seu aguardo!!
Abracos!!

**Comment by robsontenorio** [comment]
@frital hi there. Could you please include tests?

I am not sure about the flow. With tests we could review it.

**Review by hsuan1117 — APPROVED** [review]

**Comment by OfficialBAMM** [comment]
I'd like to have this merged as well. 

Can I create the tests for you so you can merge the request?

**Comment by robsontenorio** [comment]
@OfficialBAMM  for sure! We need test to keep consistence through all features :)

**Comment by OfficialBAMM** [comment]
Created the PR. Let me know what you think!

**Comment by leidison** [comment]
@frital,

I was already about to implement an egalitarian solution.

Congratulations for the initiative. I need this feature.

**Comment by robsontenorio** [comment]
Could you guys test master branch with this feature DISABLED if everything is ok, before I release a tag ?

**Comment by OfficialBAMM** [comment]
Just tested it on my application with an empty string or removed at all. Both worked for me.

Given a random string gives a `Call to undefined method App\\Providers\\KeycloakEloquentUserProvider::randomFunction()`. 
This should probably give a better error. If you're interested I could make a PR for it.

Looking at the code, I see no reason why it shouldn't work for existing installations.

**Pull request merged**
