### PR TITLE
Prepare to update all 

### PR DESCRIPTION
**Pull request by robsontenorio**
Resolves #75 #70 #66 #67 #63  #64 

- Update all dependencies
- Add `leeway` option to prevent token excepetion due to network issues 
  - #38
- Add option `api_token` to get an alternative token
  - #64 
  - #63
- Add option `ignore_resources_validation` to ignore resource validation  
  - #66 
  - #67
- Add phpcsfixer
- Add github actions
- Add VSCODE devcontainer
- Update README

Inspired by #75 . Big thansks to @Nizari effort  !

Just opted to not include all boilerplate from #75 in order to keep things simple.  After this MR I am able to review anothers MRs.

### CODE REVIEW

**Comment by Nizari** [comment]
> Resolves #75 #70
> 
> * Update all dependencies
> * Add `leeway` option to prevent token excepetion due to network issues
> * Add phpcsfixer
> * Add github actions
> * Add VSCODE devcontainer
> * Update README
> 
> Inspired by #75 . Big thansks to @Nizari effort !
> 
> Just opted to not include all boilerplate from #75 in order to keep things simple. After this MR I am able to review anothers MRs.

Haha I can understand that ;) you can close my PR when you want

**Comment by robsontenorio** [comment]
@Nizari  I have solved many gotchas after updating versions by looking up your MR

**Comment by AubreyHewes** [comment]
Wow, Just seeing this now. Why did you incorporate the PRs as own changes?

**Comment by AubreyHewes** [comment]
Also never commit everything with "WIP".. say what you are doing as it explains the code changes i.e. took this from so and so. Doing this because of this.. etc.

Also if WIP why commit and push so much? Just push when the WIP is done?  Locally can reset head etc.

**Comment by AubreyHewes** [comment]
All in all I am disappointed I actually cared/took the time to give a PR to this project.

**Pull request merged**
